[electrum]
ServerHost = "electrumx-server.tbtc.svc.cluster.local"
ServerPort = "50002"

[blockcypher]
Token = "d195ca15455f42b7842abd7c691191c9"
Coin = "btc"
Chain = "test3"

[ethereum]
URL = "ws://eth-tx.test.keep.network:8546"

[ethereum.account]
KeyFile = "/mnt/keep-tecdsa/eth/eth_account_keyfile"

[ethereum.ContractAddresses]
ECDSAKeepFactory = "0x9684Ea6608Ec757F92fa217341c6765870DAc664"

[Storage]
DataDir = "/mnt/keep-tecdsa/data"
